blank_issues_enabled: false
contact_links:
  - name: ARX Documentation
    url: https://vladimir-sama.github.io/arx-lang/
    about: Check the official documentation for language reference and examples
  - name: VS Code Extension
    url: https://github.com/vladimir-sama/arx-vscode/
    about: Issues related to the VS Code extension for ARX